---
sudo: false
language: bash
services:
  - docker
before_install:
  - docker pull jekyll/jekyll:3.8.5
script:
  - docker run --rm -v "$PWD:/srv/jekyll" jekyll/jekyll:3.8.5 test/travis-ci
branches:  # necessary to force builds of gh-pages:
  only:
    - gh-pages
    - "/.*/"
