---
sudo: required
language: bash
services:
  - docker
before_install:
  - docker pull jekyll/jekyll:3.8.5
  - docker create --name yadm-website --entrypoint test/travis-ci jekyll/jekyll:3.8.5
  - docker cp ./ yadm-website:/srv/jekyll
script:
  - docker start yadm-website -a
branches:  # necessary to force builds of gh-pages:
  only:
    - gh-pages
    - "/.*/"
